-- MySQL Script generated by MySQL Workbench
-- Wed Nov 28 09:17:30 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema reserveringen-R-us
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema reserveringen-R-us
-- -----------------------------------------------------
DROP DATABASE IF EXISTS `reserveringen-R-us`;
CREATE DATABASE IF NOT EXISTS `reserveringen-R-us` DEFAULT CHARACTER SET utf8 ;
USE `reserveringen-R-us`;

-- -----------------------------------------------------
-- Table `reserveringen-R-us`.`Reserveringen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reserveringen-R-us`.`Reserveringen` (
  `reserveringenID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tafelnummer` INT NULL,
  `datum` DATE NULL,
  `tijd` TIME NULL,
  `klant voornaam` VARCHAR(70) NULL,
  `klant achternaam` VARCHAR(70) NULL,
  `status` VARCHAR(40) NULL,
  `datum van toevoegen` DATE NULL,
  `aantal kinderen` INT NULL,
  `aantal totaal` INT NULL,
  `allergieen` VARCHAR(45) NULL,
  `opmerkingen` VARCHAR(45) NULL,
  UNIQUE INDEX `reserveringenID_UNIQUE` (`reserveringenID` ASC),
  PRIMARY KEY (`reserveringenID`));

  CREATE TABLE IF NOT EXISTS `reserveringen-R-us`.`Bestellingen` (
  `bestellingID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `reserveringenID` INT UNSIGNED NOT NULL,
  `tafelnummer` INT NULL,
  `datum` DATE NULL,
  `tijd` TIME NULL,
  `menu item code` INT NULL,
  `aantal` INT NULL,
  `prijs` DECIMAL(6,2) NULL,
  PRIMARY KEY (`bestellingID`),
  UNIQUE INDEX `bestellingID_UNIQUE` (`bestellingID` ASC),
  INDEX `fk_Bestellingen_Reserveringen_idx` (`reserveringenID` ASC),
  CONSTRAINT `fk_Bestellingen_Reserveringen`
    FOREIGN KEY (`reserveringenID`)
    REFERENCES `reserveringen-R-us`.`Reserveringen` (`reserveringenID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

INSERT INTO `reserveringen-R-us`.`Reserveringen` (`tafelnummer`, `datum`, `tijd`, `klant voornaam`, `klant achternaam`, `status`, `datum van toevoegen`, `aantal totaal`, `aantal kinderen`, `allergieen`, `opmerkingen`)
VALUES (1, '2018-12-01', '15:00', 'alex', 'is gay lmao', 'gay', '1980-5-7', 25, 15, '', ''),
(34, "1980-7-10", '111:00', 'struik', 'rover', 'in behandeling', '1980-4-7', 25, 15, '', ''),
(65, '1980-2-10', '19:00', 'struik', 'rover', 'in behandeling', '1980-3-7', 25, 15, '', ''),
(4, '1980-5-10', '17:00', 'struik', 'rover', 'in behandeling', '1980-5-7', 25, 15, '', '');


INSERT INTO `reserveringen-R-us`.`Bestellingen` (reserveringenID, tafelnummer, datum, tijd, `menu item code`, aantal, prijs)
VALUES (4, 3 ,'1945-12-01', '15:00', 2, 1, 19.95),
(7, 4, "1946-7-10", '11:00', 5, 1, 1.95),
(2, 1, '1947-2-10', '19:00', 9, 3, 2.99),
(1, 0, '1948-5-10', '17:00', 1, 2, 0.10);
